cellsociety_team15: view.TriangleGrid Class Reference
view.TriangleGrid Class Reference
Public Member Functions
TriangleGrid (double gridWidth, double gridHeight, Shape[][] colorGrid)
Shape addShape (boolean stroke, double heightOfShape, double widthOfShape, int i, int j)
Public Member Functions inherited from view.ShapeGrid
ShapeGrid (double gridWidth, double gridHeight, Shape colorGrid[][])
Shape[][] getColorGrid ()
Group createGrid (boolean stroke, double heightOfShape, double widthOfShape)
abstract Shape addShape (boolean stroke, double heightOfSquare, double widthOfSquare, int i, int j)
Private Member Functions
Polygon makeNewTriangle (double heightOfShape, double widthOfShape)
void translateTri (double heightOfShape, double widthOfShape, int i, int j, Polygon tri1)
boolean isOdd (int i)
void format (double heightOfShape, double widthOfShape, int i, int j, Polygon tri1)
Polygon makeNewStrokeTriangle (double heightOfShape, double widthOfShape)
Additional Inherited Members
Protected Attributes inherited from view.ShapeGrid
double myGridWidth
double myGridHeight
Detailed Description
Definition at line 7 of file TriangleGrid.java.
Constructor & Destructor Documentation
view.TriangleGrid.TriangleGrid (double gridWidth, double gridHeight, Shape colorGrid[][])
Definition at line 9 of file TriangleGrid.java.
Member Function Documentation
Shape view.TriangleGrid.addShape (boolean stroke, double heightOfShape, double widthOfShape, int i, int j)
Definition at line 14 of file TriangleGrid.java.
References view.TriangleGrid.format(), view.TriangleGrid.makeNewStrokeTriangle(), view.TriangleGrid.makeNewTriangle(), and view.TriangleGrid.translateTri().
void view.TriangleGrid.format (double heightOfShape, double widthOfShape, int i, int j, Polygon tri1) private
Definition at line 53 of file TriangleGrid.java.
Referenced by view.TriangleGrid.addShape().
boolean view.TriangleGrid.isOdd (int i) private
Definition at line 49 of file TriangleGrid.java.
Referenced by view.TriangleGrid.translateTri().
Polygon view.TriangleGrid.makeNewStrokeTriangle (double heightOfShape, double widthOfShape) private
Definition at line 59 of file TriangleGrid.java.
Referenced by view.TriangleGrid.addShape().
Polygon view.TriangleGrid.makeNewTriangle (double heightOfShape, double widthOfShape) private
Definition at line 29 of file TriangleGrid.java.
Referenced by view.TriangleGrid.addShape().
void view.TriangleGrid.translateTri (double heightOfShape, double widthOfShape, int i, int j, Polygon tri1) private
Definition at line 38 of file TriangleGrid.java.
References view.TriangleGrid.isOdd().
Referenced by view.TriangleGrid.addShape().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team15/repository/src/view/TriangleGrid.java