cellsociety_team15: model.patches.Patch Class Reference
model.patches.Patch Class Reference
Public Member Functions
Patch (int x, int y)
double getProperty (String property)
void updateProperty (String property, double value)
void setCell (Cell cell)
Cell getCell ()
void setNeighbors (List< Patch > neighbors)
List< Patch > getNeighbors ()
void update ()
Color getColor ()
Protected Attributes
Cell myCell
List< Patch > myNeighbors
Map< String, Double > myPatchPropertyMap
int myX
int myY
Detailed Description
Definition at line 9 of file Patch.java.
Constructor & Destructor Documentation
model.patches.Patch.Patch (int x, int y)
Definition at line 16 of file Patch.java.
Member Function Documentation
Cell model.patches.Patch.getCell ()
Definition at line 33 of file Patch.java.
References model.patches.Patch.myCell.
Referenced by model.simulations.SimulationFire.setParameter(), model.simulations.SimulationSegregation.setParameter(), model.simulations.SimulationPredator.setParameter(), model.simulations.SimulationPredator.SimulationPredator(), model.simulations.Simulation.updateColorGrid(), model.simulations.SimulationSugarscape.updateGrid(), model.simulations.SimulationPredator.updateGrid(), model.simulations.SimulationSegregation.updateGrid(), and model.simulations.Simulation.updateNeighborSquare().
Color model.patches.Patch.getColor ()
Definition at line 48 of file Patch.java.
Referenced by model.simulations.Simulation.updateColorGrid().
List<Patch> model.patches.Patch.getNeighbors ()
Definition at line 41 of file Patch.java.
References model.patches.Patch.myNeighbors.
double model.patches.Patch.getProperty (String property)
Definition at line 22 of file Patch.java.
void model.patches.Patch.setCell (Cell cell)
Definition at line 29 of file Patch.java.
Referenced by model.simulations.SimulationSegregation.moveAgent(), model.simulations.Simulation.setupGrid(), model.simulations.SimulationLife.updateGrid(), model.simulations.SimulationSugarscape.updateGrid(), model.simulations.SimulationPredator.updateGrid(), and model.simulations.SimulationFire.updateGrid().
void model.patches.Patch.setNeighbors (List< Patch > neighbors)
Definition at line 37 of file Patch.java.
Referenced by model.simulations.Simulation.fillPatchGrid().
void model.patches.Patch.update ()
Definition at line 45 of file Patch.java.
void model.patches.Patch.updateProperty (String property, double value)
Definition at line 26 of file Patch.java.
Member Data Documentation
Cell model.patches.Patch.myCell protected
Definition at line 10 of file Patch.java.
Referenced by model.patches.Patch.getCell().
List<Patch> model.patches.Patch.myNeighbors protected
Definition at line 11 of file Patch.java.
Referenced by model.patches.Patch.getNeighbors().
Map<String,Double> model.patches.Patch.myPatchPropertyMap protected
Definition at line 12 of file Patch.java.
Referenced by model.patches.SugarPatch.getColor(), model.patches.SugarPatch.SugarPatch(), and model.patches.SugarPatch.update().
int model.patches.Patch.myX protected
Definition at line 13 of file Patch.java.
int model.patches.Patch.myY protected
Definition at line 14 of file Patch.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team15/repository/src/model/patches/Patch.java