cellsociety_team15: controller.CellSocietyController Class Reference
controller.CellSocietyController Class Reference
Public Member Functions
CellSocietyController (int width, int height, Stage stage)
Scene getScene ()
void setFrameRate (int frameRate)
KeyFrame getKeyFrame (int frameRate)
void generateRandomGrid (int gridHeight, int gridWidth, String simName)
void generateProbabilityRandomGrid (int gridHeight, int gridWidth, String simName, HashMap< Integer, Integer > probabilities)
void transitionToFileLoaderScreen ()
void stepThroughSimulation ()
void changeSimulationSpeed (boolean speedUp)
void stopOrStart (boolean stopStart)
void manageTimeline (Timeline animationTimeline, int frameRate)
void changeSimulationParameters (String string, double new_val)
Private Member Functions
void displaySplashScreen (int width, int height)
void update ()
void readXML (File XMLFile) throws InvalidParameterException
void restartSimulation ()
void pauseSimulation ()
void transitionToSimulation () throws ValueException
void initializeSimulationScreen ()
void initializeSimulation (String simName) throws ValueException
Private Attributes
Simulation myCurrentSimulation
SimulationScreen myCurrentSimulationScreen
Scene myScene
Group myGroup
HashMap< String, String > myParameters = new HashMap<String, String>()
Map< String, String > myStyles = new HashMap<String, String>()
Integer myGrid [][]
int myFrameRate
Timeline myTimeline
Stage myStage
ResourceBundle myProperties
Detailed Description
Main controller that is called by main Handles the upper-most level of CellSociety
Author
Sid
Definition at line 33 of file CellSocietyController.java.
Constructor & Destructor Documentation
controller.CellSocietyController.CellSocietyController (int width, int height, Stage stage)
Definition at line 47 of file CellSocietyController.java.
References controller.CellSocietyController.displaySplashScreen().
Member Function Documentation
void controller.CellSocietyController.changeSimulationParameters (String string, double new_val)
Definition at line 266 of file CellSocietyController.java.
References model.simulations.Simulation.setParameter().
Referenced by view.SideMenu.addOptionsPanel().
void controller.CellSocietyController.changeSimulationSpeed (boolean speedUp)
if speedUp is true, then we speed up by factor of 2 if false, we slow down by factor of 2
Parameters
upOrDown
Definition at line 176 of file CellSocietyController.java.
References controller.CellSocietyController.getKeyFrame(), and controller.CellSocietyController.myFrameRate.
Referenced by view.TopMenu.addSlowDownButton(), and view.TopMenu.addSpeedUpButton().
void controller.CellSocietyController.displaySplashScreen (int width, int height) private
Extracted method that displays splash screen Called from constructor to set up first screen
Definition at line 58 of file CellSocietyController.java.
References view.SplashScreen.getNode().
Referenced by controller.CellSocietyController.CellSocietyController().
void controller.CellSocietyController.generateProbabilityRandomGrid (int gridHeight, int gridWidth, String simName, HashMap< Integer, Integer > probabilities)
Method to be called from view Generates random grid based on probabilities passed in in a map Default values will be used for parameters
Parameters
gridHeight
gridWidth
simName
probabilities
Definition at line 112 of file CellSocietyController.java.
References controller.ProbabilitySimGenerator.getGrid(), controller.ProbabilitySimGenerator.getParameters(), and controller.CellSocietyController.transitionToSimulation().
Referenced by view.SplashScreen.addProbabilityText().
void controller.CellSocietyController.generateRandomGrid (int gridHeight, int gridWidth, String simName)
Method to be called from the view Generates fully random grid from parameters passed in Default values will be used for parameters
Parameters
gridHeight
gridWidth
simName
fullyRandom
Definition at line 96 of file CellSocietyController.java.
References controller.RandomSimGenerator.getGrid(), controller.RandomSimGenerator.getParameters(), and controller.CellSocietyController.transitionToSimulation().
Referenced by view.SplashScreen.displayAskInformatio().
KeyFrame controller.CellSocietyController.getKeyFrame (int frameRate)
Definition at line 73 of file CellSocietyController.java.
References controller.CellSocietyController.update().
Referenced by controller.CellSocietyController.changeSimulationSpeed(), and controller.CellSocietyController.manageTimeline().
Scene controller.CellSocietyController.getScene ()
Definition at line 65 of file CellSocietyController.java.
References controller.CellSocietyController.myScene.
Referenced by controller.Main.start().
void controller.CellSocietyController.initializeSimulation (String simName) throws ValueException private
Initializes the model
Parameters
simName
Definition at line 223 of file CellSocietyController.java.
Referenced by controller.CellSocietyController.transitionToSimulation().
void controller.CellSocietyController.initializeSimulationScreen () private
Initializes the view.
Definition at line 212 of file CellSocietyController.java.
References view.SimulationScreen.getNode(), controller.Main.HEIGHT, view.SimulationScreen.initSimScreen(), and controller.Main.WIDTH.
Referenced by controller.CellSocietyController.transitionToSimulation().
void controller.CellSocietyController.manageTimeline (Timeline animationTimeline, int frameRate)
Method to start and manage the animation timeline
Parameters
animationTimeline
frameRate
Definition at line 258 of file CellSocietyController.java.
References controller.CellSocietyController.getKeyFrame().
Referenced by controller.Main.start().
void controller.CellSocietyController.pauseSimulation () private
Definition at line 196 of file CellSocietyController.java.
Referenced by controller.CellSocietyController.stopOrStart().
void controller.CellSocietyController.readXML (File XMLFile) throws InvalidParameterException private
Reads an XML file and stores the Int grid and Parameters Catches file error exceptions and takes user back to load screen
Definition at line 123 of file CellSocietyController.java.
References controller.XMLParser.getGrid(), controller.XMLParser.getParameters(), controller.CellSocietyController.transitionToFileLoaderScreen(), and controller.CellSocietyController.transitionToSimulation().
Referenced by controller.CellSocietyController.transitionToFileLoaderScreen().
void controller.CellSocietyController.restartSimulation () private
Definition at line 192 of file CellSocietyController.java.
Referenced by controller.CellSocietyController.stopOrStart().
void controller.CellSocietyController.setFrameRate (int frameRate)
Definition at line 69 of file CellSocietyController.java.
Referenced by controller.Main.start().
void controller.CellSocietyController.stepThroughSimulation ()
Steps through simulation one frame at a time.
Definition at line 165 of file CellSocietyController.java.
Referenced by view.TopMenu.addStepButton().
void controller.CellSocietyController.stopOrStart (boolean stopStart)
Tells simulation to pause or restart
Parameters
stopStart
Definition at line 244 of file CellSocietyController.java.
References controller.CellSocietyController.pauseSimulation(), and controller.CellSocietyController.restartSimulation().
Referenced by view.TopMenu.addStopStartButton(), and controller.CellSocietyController.transitionToSimulation().
void controller.CellSocietyController.transitionToFileLoaderScreen ()
Method called when the load button has been pressed Opens up the file loader screen by calling the view class Gets a File that will then be passed into XMLParser.
Definition at line 155 of file CellSocietyController.java.
References view.FileLoaderScreen.getFile(), view.FileLoaderScreen.getNode(), and controller.CellSocietyController.readXML().
Referenced by view.TopMenu.addLoadButton(), view.SplashScreen.addLoadButton(), and controller.CellSocietyController.readXML().
void controller.CellSocietyController.transitionToSimulation () throws ValueException private
Called after the XML file has been made. Transitions to new simulation
Definition at line 203 of file CellSocietyController.java.
References controller.CellSocietyController.initializeSimulation(), controller.CellSocietyController.initializeSimulationScreen(), and controller.CellSocietyController.stopOrStart().
Referenced by controller.CellSocietyController.generateProbabilityRandomGrid(), controller.CellSocietyController.generateRandomGrid(), and controller.CellSocietyController.readXML().
void controller.CellSocietyController.update () private
Update method called every frame Calls simulation's update method
Definition at line 81 of file CellSocietyController.java.
References model.simulations.Simulation.updateGrid().
Referenced by controller.CellSocietyController.getKeyFrame().
Member Data Documentation
Simulation controller.CellSocietyController.myCurrentSimulation private
Definition at line 35 of file CellSocietyController.java.
SimulationScreen controller.CellSocietyController.myCurrentSimulationScreen private
Definition at line 36 of file CellSocietyController.java.
int controller.CellSocietyController.myFrameRate private
Definition at line 42 of file CellSocietyController.java.
Referenced by controller.CellSocietyController.changeSimulationSpeed().
Integer controller.CellSocietyController.myGrid[][] private
Definition at line 41 of file CellSocietyController.java.
Group controller.CellSocietyController.myGroup private
Definition at line 38 of file CellSocietyController.java.
HashMap<String, String> controller.CellSocietyController.myParameters = new HashMap<String, String>() private
Definition at line 39 of file CellSocietyController.java.
ResourceBundle controller.CellSocietyController.myProperties private
Definition at line 45 of file CellSocietyController.java.
Scene controller.CellSocietyController.myScene private
Definition at line 37 of file CellSocietyController.java.
Referenced by controller.CellSocietyController.getScene().
Stage controller.CellSocietyController.myStage private
Definition at line 44 of file CellSocietyController.java.
Map<String, String> controller.CellSocietyController.myStyles = new HashMap<String, String>() private
Definition at line 40 of file CellSocietyController.java.
Timeline controller.CellSocietyController.myTimeline private
Definition at line 43 of file CellSocietyController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team15/repository/src/controller/CellSocietyController.java