cellsociety_team15: controller.SimGenerator Class Reference
controller.SimGenerator Class Reference abstract
Public Member Functions
SimGenerator (int gridHeight, int gridWidth, String simName, HashMap< Integer, Integer > probabilities, String gridType)
Integer[][] getGrid ()
HashMap< String, String > getParameters ()
Protected Member Functions
abstract void createGrid (Integer[][] grid)
Protected Attributes
Integer[][] myGrid
HashMap< String, String > myParameters = new HashMap<String, String>()
String mySimName
Random myRandom = new Random()
ResourceBundle myProperties
Detailed Description
Definition at line 10 of file SimGenerator.java.
Constructor & Destructor Documentation
controller.SimGenerator.SimGenerator (int gridHeight, int gridWidth, String simName, HashMap< Integer, Integer > probabilities, String gridType)
Definition at line 18 of file SimGenerator.java.
Member Function Documentation
abstract void controller.SimGenerator.createGrid (Integer grid[][]) abstract protected
Integer [][] controller.SimGenerator.getGrid ()
Definition at line 27 of file SimGenerator.java.
References controller.SimGenerator.myGrid.
Referenced by controller.CellSocietyController.generateGrid().
HashMap<String, String> controller.SimGenerator.getParameters ()
Definition at line 31 of file SimGenerator.java.
References controller.SimGenerator.myParameters.
Referenced by controller.CellSocietyController.generateGrid().
Member Data Documentation
Integer [][] controller.SimGenerator.myGrid protected
Definition at line 12 of file SimGenerator.java.
Referenced by controller.ProbabilitySimGenerator.generateCellValue(), controller.SimGenerator.getGrid(), controller.ProbabilitySimGenerator.ProbabilitySimGenerator(), and controller.RandomSimGenerator.RandomSimGenerator().
HashMap<String, String> controller.SimGenerator.myParameters = new HashMap<String, String>() protected
Definition at line 13 of file SimGenerator.java.
Referenced by controller.SimGenerator.getParameters().
ResourceBundle controller.SimGenerator.myProperties protected
Definition at line 16 of file SimGenerator.java.
Referenced by controller.RandomSimGenerator.createGrid().
Random controller.SimGenerator.myRandom = new Random() protected
Definition at line 15 of file SimGenerator.java.
Referenced by controller.RandomSimGenerator.createGrid(), and controller.ProbabilitySimGenerator.generateCellValue().
String controller.SimGenerator.mySimName protected
Definition at line 14 of file SimGenerator.java.
Referenced by controller.RandomSimGenerator.createGrid().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team15/repository/src/controller/SimGenerator.java