cellsociety_team15: model.cells.Cell Class Reference
model.cells.Cell Class Reference abstract
Public Member Functions
abstract Color getColor ()
void setNeighbors (List< Cell > neighbors)
Cell ()
Map< String, Double > viewProperties ()
void setCoords (int x, int y)
int getX ()
int getY ()
void setProperty (String property, Double value)
abstract Cell update ()
void setPatch (Patch patch)
Protected Attributes
List< Cell > myNeighbors
Map< String, Double > myPropertyMap
int myX
int myY
Patch myPatch
Detailed Description
This is the cell superclass All other cells are subclasses of this It holds a hashmap with all of the properties for each cell
Author
Janan
Definition at line 17 of file Cell.java.
Constructor & Destructor Documentation
model.cells.Cell.Cell ()
Definition at line 29 of file Cell.java.
Member Function Documentation
abstract Color model.cells.Cell.getColor () abstract
Referenced by model.simulations.Simulation.updateColorGrid().
int model.cells.Cell.getX ()
Definition at line 49 of file Cell.java.
References model.cells.Cell.myX.
Referenced by model.cells.PredatorCellFish.moveSquareTo(), model.cells.PredatorCellShark.moveSquareTo(), model.simulations.SimulationSugarscape.updateGrid(), and model.simulations.SimulationPredator.updateGrid().
int model.cells.Cell.getY ()
Definition at line 53 of file Cell.java.
References model.cells.Cell.myY.
Referenced by model.cells.PredatorCellFish.moveSquareTo(), model.cells.PredatorCellShark.moveSquareTo(), model.simulations.SimulationSugarscape.updateGrid(), and model.simulations.SimulationPredator.updateGrid().
void model.cells.Cell.setCoords (int x, int y)
Definition at line 44 of file Cell.java.
Referenced by model.cells.PredatorCellFish.moveSquareTo(), model.cells.PredatorCellShark.moveSquareTo(), model.simulations.SimulationPredator.SimulationPredator(), model.cells.PredatorCellShark.update(), and model.simulations.SimulationPredator.updateGrid().
void model.cells.Cell.setNeighbors (List< Cell > neighbors)
Definition at line 25 of file Cell.java.
Referenced by model.simulations.Simulation.updateNeighborSquare().
void model.cells.Cell.setPatch (Patch patch)
Definition at line 66 of file Cell.java.
Referenced by model.simulations.Simulation.setupGrid().
void model.cells.Cell.setProperty (String property, Double value)
Definition at line 57 of file Cell.java.
Referenced by model.simulations.SimulationFire.setParameter(), model.simulations.SimulationSegregation.setParameter(), and model.simulations.SimulationPredator.setParameter().
abstract Cell model.cells.Cell.update () abstract
Referenced by model.simulations.SimulationSugarscape.updateGrid(), model.simulations.SimulationPredator.updateGrid(), and model.simulations.SimulationSegregation.updateGrid().
Map<String,Double> model.cells.Cell.viewProperties ()
Definition at line 36 of file Cell.java.
Referenced by model.cells.FireCell.calculateProbability(), model.cells.FireCellTree.checkStatus(), model.cells.LifeCell.update(), model.simulations.SimulationSugarscape.updateGrid(), and model.simulations.SimulationPredator.updateGrid().
Member Data Documentation
List<Cell> model.cells.Cell.myNeighbors protected
Definition at line 18 of file Cell.java.
Referenced by model.cells.FireCellTree.checkStatus(), model.cells.AgentCell.isSatisfied(), model.cells.PredatorCellFish.moveSquareTo(), model.cells.PredatorCellShark.moveSquareTo(), model.cells.AgentCellO.returnCount(), model.cells.AgentCellX.returnCount(), and model.cells.LifeCell.update().
Patch model.cells.Cell.myPatch protected
Definition at line 22 of file Cell.java.
Map<String,Double> model.cells.Cell.myPropertyMap protected
Definition at line 19 of file Cell.java.
Referenced by model.cells.AgentCellEmpty.AgentCellEmpty(), model.cells.AgentCellO.AgentCellO(), model.cells.AgentCellX.AgentCellX(), model.cells.PredatorCell.decrementBreeding(), model.cells.FireCellBurning.FireCellBurning(), model.cells.FireCellEmpty.FireCellEmpty(), model.cells.FireCellTree.FireCellTree(), model.cells.LifeCellAlive.LifeCellAlive(), model.cells.LifeCellDead.LifeCellDead(), model.cells.PredatorCellShark.moveSquareTo(), model.cells.PredatorCell.PredatorCell(), model.cells.PredatorCellEmpty.PredatorCellEmpty(), model.cells.PredatorCellFish.PredatorCellFish(), model.cells.PredatorCellShark.PredatorCellShark(), model.cells.SugarCellAgent.SugarCellAgent(), model.cells.SugarCellAgent.update(), model.cells.AgentCellO.update(), and model.cells.AgentCellX.update().
int model.cells.Cell.myX protected
Definition at line 20 of file Cell.java.
Referenced by model.cells.Cell.getX(), model.cells.PredatorCellShark.moveSquareTo(), and model.cells.PredatorCellShark.update().
int model.cells.Cell.myY protected
Definition at line 21 of file Cell.java.
Referenced by model.cells.Cell.getY(), model.cells.PredatorCellShark.moveSquareTo(), and model.cells.PredatorCellShark.update().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team15/repository/src/model/cells/Cell.java