cellsociety_team15: view.SplashScreen Class Reference
view.SplashScreen Class Reference
Public Member Functions
SplashScreen (CellSocietyController controller)
Group getNode (int width, int height)
Private Member Functions
void addProbablityButton ()
void displayAskInformatio (boolean probability)
void addProbabilityText (int numTextFields, TextField[] dimensions, String simName)
void removeAskScreenNodes ()
TextField addSimulationNameText ()
TextField[] addDimensionsText ()
void removeButtons ()
void addRandomButton ()
void addTitle ()
void addLoadButton ()
void formatNode (Node node, double width, double height, int scale)
Private Attributes
Group myRoot
int myWidth
int myHeight
CellSocietyController myController
ArrayList< Button > myButtons
ArrayList< Node > myAskScreenNodes
Static Private Attributes
static final int SPLASH_TEXT_SIZE = 5
static final int LOAD_BUTTON_SIZE = 1
static ResourceBundle myProperties
Detailed Description
This function will initialize the splash screen. The splash screen needs to display text that says the title of the program, which will come from the class that returns the input stream of the property files.
Author
Sunjeev
Definition at line 24 of file SplashScreen.java.
Constructor & Destructor Documentation
view.SplashScreen.SplashScreen (CellSocietyController controller)
Definition at line 35 of file SplashScreen.java.
Member Function Documentation
TextField [] view.SplashScreen.addDimensionsText () private
Definition at line 185 of file SplashScreen.java.
Referenced by view.SplashScreen.displayAskInformatio().
void view.SplashScreen.addLoadButton () private
This function will add the button to the scene. This includes all the formatting of the button. It will have to get the button's position from the .properties file.
Definition at line 247 of file SplashScreen.java.
References view.SplashScreen.formatNode(), and controller.CellSocietyController.transitionToFileLoaderScreen().
Referenced by view.SplashScreen.getNode().
void view.SplashScreen.addProbabilityText (int numTextFields, TextField[] dimensions, String simName) private
Definition at line 116 of file SplashScreen.java.
References controller.CellSocietyController.generateProbabilityRandomGrid(), and view.SplashScreen.removeAskScreenNodes().
Referenced by view.SplashScreen.displayAskInformatio().
void view.SplashScreen.addProbablityButton () private
collects integers for probability distribution
Definition at line 65 of file SplashScreen.java.
References view.SplashScreen.displayAskInformatio(), and view.SplashScreen.formatNode().
Referenced by view.SplashScreen.getNode().
void view.SplashScreen.addRandomButton () private
remove other buttons, and have user select grid height, width, and type of simulation
Definition at line 223 of file SplashScreen.java.
References view.SplashScreen.displayAskInformatio(), and view.SplashScreen.formatNode().
Referenced by view.SplashScreen.getNode().
TextField view.SplashScreen.addSimulationNameText () private
Definition at line 166 of file SplashScreen.java.
Referenced by view.SplashScreen.displayAskInformatio().
void view.SplashScreen.addTitle () private
This function will add the title in. This is example code of what it might do. It will have to get the name of the program from the .properties file which will then dictate where it goes.
Definition at line 236 of file SplashScreen.java.
References view.SplashScreen.formatNode().
Referenced by view.SplashScreen.getNode().
void view.SplashScreen.displayAskInformatio (boolean probability) private
Definition at line 74 of file SplashScreen.java.
References view.SplashScreen.addDimensionsText(), view.SplashScreen.addProbabilityText(), view.SplashScreen.addSimulationNameText(), controller.CellSocietyController.generateRandomGrid(), and view.SplashScreen.removeButtons().
Referenced by view.SplashScreen.addProbablityButton(), and view.SplashScreen.addRandomButton().
void view.SplashScreen.formatNode (Node node, double width, double height, int scale) private
Definition at line 258 of file SplashScreen.java.
Referenced by view.SplashScreen.addLoadButton(), view.SplashScreen.addProbablityButton(), view.SplashScreen.addRandomButton(), and view.SplashScreen.addTitle().
Group view.SplashScreen.getNode (int width, int height)
This function will initialize the splash screen. The splash screen needs to display text that says the title of the program, which will come from the class that returns the input stream of the property files.
This function will also have to have add button that takes it to the FileLoaderScreen class.
Definition at line 45 of file SplashScreen.java.
References view.SplashScreen.addLoadButton(), view.SplashScreen.addProbablityButton(), view.SplashScreen.addRandomButton(), view.SplashScreen.addTitle(), and view.SplashScreen.myRoot.
Referenced by controller.CellSocietyController.displaySplashScreen().
void view.SplashScreen.removeAskScreenNodes () private
Definition at line 158 of file SplashScreen.java.
Referenced by view.SplashScreen.addProbabilityText().
void view.SplashScreen.removeButtons () private
Definition at line 212 of file SplashScreen.java.
Referenced by view.SplashScreen.displayAskInformatio().
Member Data Documentation
final int view.SplashScreen.LOAD_BUTTON_SIZE = 1 static private
Definition at line 26 of file SplashScreen.java.
ArrayList<Node> view.SplashScreen.myAskScreenNodes private
Definition at line 32 of file SplashScreen.java.
ArrayList<Button> view.SplashScreen.myButtons private
Definition at line 31 of file SplashScreen.java.
CellSocietyController view.SplashScreen.myController private
Definition at line 30 of file SplashScreen.java.
int view.SplashScreen.myHeight private
Definition at line 29 of file SplashScreen.java.
ResourceBundle view.SplashScreen.myProperties static private
Definition at line 33 of file SplashScreen.java.
Group view.SplashScreen.myRoot private
Definition at line 27 of file SplashScreen.java.
Referenced by view.SplashScreen.getNode().
int view.SplashScreen.myWidth private
Definition at line 28 of file SplashScreen.java.
final int view.SplashScreen.SPLASH_TEXT_SIZE = 5 static private
Definition at line 25 of file SplashScreen.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team15/repository/src/view/SplashScreen.java