cellsociety_team15: model.cells.FireCell Class Reference
model.cells.FireCell Class Reference abstract
Public Member Functions
FireCell ()
FireCell update ()
boolean calculateProbability (Cell cell)
Public Member Functions inherited from model.cells.Cell
abstract Color getColor ()
void setNeighbors (List< Cell > neighbors)
Cell ()
Map< String, Double > viewProperties ()
void setCoords (int x, int y)
int getX ()
int getY ()
void setProperty (String property, Double value)
abstract Cell update ()
void setPatch (Patch patch)
Protected Member Functions
abstract FireCell checkStatus ()
Protected Attributes
Random myRandom
Protected Attributes inherited from model.cells.Cell
List< Cell > myNeighbors
Map< String, Double > myPropertyMap
int myX
int myY
Patch myPatch
Detailed Description
This is the square superclass for Fire simulation. It holds the method to update each cell It also holds the method to calculate the probability that a cell will catch fire
Author
Sunjeev and Sid
Definition at line 14 of file FireCell.java.
Constructor & Destructor Documentation
model.cells.FireCell.FireCell ()
Definition at line 18 of file FireCell.java.
Member Function Documentation
boolean model.cells.FireCell.calculateProbability (Cell cell)
Definition at line 30 of file FireCell.java.
References model.cells.Cell.viewProperties().
abstract FireCell model.cells.FireCell.checkStatus () abstract protected
Referenced by model.cells.FireCell.update().
FireCell model.cells.FireCell.update ()
Returns
the current state of the tree after checking with neighbors determined by making a new SquareFire class
Definition at line 26 of file FireCell.java.
References model.cells.FireCell.checkStatus().
Member Data Documentation
Random model.cells.FireCell.myRandom protected
Definition at line 16 of file FireCell.java.
Referenced by model.cells.FireCellTree.calculateProbability().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team15/repository/src/model/cells/FireCell.java