cellsociety_team15: model.simulations.SimulationSugarscape Class Reference
model.simulations.SimulationSugarscape Class Reference
Public Member Functions
SimulationSugarscape (Map< String, String > paramMap, Map< String, String > styleMap, Integer[][] grid, SimulationScreen simScreen)
void updateGrid ()
String patchType ()
Public Member Functions inherited from model.simulations.Simulation
Simulation (Map< String, String > paramMap, Map< String, String > styleMap, Integer[][] cellGrid, SimulationScreen simScreen) throws ValueException
void setParameter (String parameter, double value)
String patchType ()
abstract void updateGrid ()
void updateNeighborSquare (int row, int column)
Package Functions
void parseMap (Map< String, String > paramMap)
void setupParameterControl ()
AbstractCellFactory getCellFactory () throws ValueException
Package Functions inherited from model.simulations.Simulation
void parseStyleMap (Map< String, String > styleMap)
abstract AbstractCellFactory getCellFactory () throws ValueException
void fillPatchGrid ()
abstract void parseMap (Map< String, String > paramMap)
void setupGrid (Integer[][] grid)
void setupParameterControl ()
void updateColorGrid ()
void updateNeighbors ()
Private Attributes
int sugarGrowBackRate
int sugarGrowBackInterval
int sugarMetabolism
int vision
int initialSugar
int numAgents
Additional Inherited Members
Protected Attributes inherited from model.simulations.Simulation
SimulationScreen myView
int gridLength
int gridWidth
Patch[][] myPatchGrid
AbstractCellFactory myCellFactory
Neighbors myNeighbors
GridRules myGridRules
String directions
Detailed Description
Definition at line 9 of file SimulationSugarscape.java.
Constructor & Destructor Documentation
model.simulations.SimulationSugarscape.SimulationSugarscape (Map< String, String > paramMap, Map< String, String > styleMap, Integer grid[][], SimulationScreen simScreen)
Definition at line 17 of file SimulationSugarscape.java.
Member Function Documentation
AbstractCellFactory model.simulations.SimulationSugarscape.getCellFactory () throws ValueException package
Definition at line 68 of file SimulationSugarscape.java.
void model.simulations.SimulationSugarscape.parseMap (Map< String, String > paramMap) package
Definition at line 24 of file SimulationSugarscape.java.
String model.simulations.SimulationSugarscape.patchType ()
Definition at line 63 of file SimulationSugarscape.java.
void model.simulations.SimulationSugarscape.setupParameterControl () package
Definition at line 34 of file SimulationSugarscape.java.
References view.SimulationScreen.createOptionsPanel(), model.simulations.Simulation.myView, model.simulations.SimulationSugarscape.sugarGrowBackInterval, model.simulations.SimulationSugarscape.sugarGrowBackRate, and model.simulations.SimulationSugarscape.sugarMetabolism.
void model.simulations.SimulationSugarscape.updateGrid ()
Definition at line 43 of file SimulationSugarscape.java.
References model.patches.Patch.getCell(), model.cells.Cell.getX(), model.cells.Cell.getY(), model.simulations.Simulation.gridLength, model.simulations.Simulation.gridWidth, model.simulations.Simulation.myPatchGrid, model.patches.Patch.setCell(), model.cells.Cell.update(), model.simulations.Simulation.updateColorGrid(), model.simulations.Simulation.updateNeighbors(), and model.cells.Cell.viewProperties().
Member Data Documentation
int model.simulations.SimulationSugarscape.initialSugar private
Definition at line 14 of file SimulationSugarscape.java.
int model.simulations.SimulationSugarscape.numAgents private
Definition at line 15 of file SimulationSugarscape.java.
int model.simulations.SimulationSugarscape.sugarGrowBackInterval private
Definition at line 11 of file SimulationSugarscape.java.
Referenced by model.simulations.SimulationSugarscape.setupParameterControl().
int model.simulations.SimulationSugarscape.sugarGrowBackRate private
Definition at line 10 of file SimulationSugarscape.java.
Referenced by model.simulations.SimulationSugarscape.setupParameterControl().
int model.simulations.SimulationSugarscape.sugarMetabolism private
Definition at line 12 of file SimulationSugarscape.java.
Referenced by model.simulations.SimulationSugarscape.setupParameterControl().
int model.simulations.SimulationSugarscape.vision private
Definition at line 13 of file SimulationSugarscape.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team15/repository/src/model/simulations/SimulationSugarscape.java