cellsociety_team15: controller.RandomSimGenerator Class Reference
controller.RandomSimGenerator Class Reference
Public Member Functions
RandomSimGenerator (int gridWidth, int gridHeight, String simName)
Integer[][] getGrid ()
HashMap< String, String > getParameters ()
Private Member Functions
void createGrid (Integer[][] grid)
Private Attributes
Integer[][] myGrid
HashMap< String, String > myParameters = new HashMap<String, String>()
String mySimName
ResourceBundle myProperties
Random myRandom = new Random()
Detailed Description
This generator creates a fully random grid Each cell's state is random
Author
Sid
Definition at line 14 of file RandomSimGenerator.java.
Constructor & Destructor Documentation
controller.RandomSimGenerator.RandomSimGenerator (int gridWidth, int gridHeight, String simName)
Constructor for the random generator Puts default values into paramMap for later use Constructor could be refactored out but decided against it due to time constraints
Parameters
gridWidth
gridHeight
simName
Definition at line 30 of file RandomSimGenerator.java.
References controller.RandomSimGenerator.createGrid().
Member Function Documentation
void controller.RandomSimGenerator.createGrid (Integer grid[][]) private
Create grid based on purely random values Grid created depending on type of simulation
Parameters
grid
Definition at line 53 of file RandomSimGenerator.java.
Referenced by controller.RandomSimGenerator.RandomSimGenerator().
Integer [][] controller.RandomSimGenerator.getGrid ()
Definition at line 40 of file RandomSimGenerator.java.
References controller.RandomSimGenerator.myGrid.
Referenced by controller.CellSocietyController.generateRandomGrid().
HashMap<String, String> controller.RandomSimGenerator.getParameters ()
Definition at line 44 of file RandomSimGenerator.java.
References controller.RandomSimGenerator.myParameters.
Referenced by controller.CellSocietyController.generateRandomGrid().
Member Data Documentation
Integer [][] controller.RandomSimGenerator.myGrid private
Definition at line 16 of file RandomSimGenerator.java.
Referenced by controller.RandomSimGenerator.getGrid().
HashMap<String, String> controller.RandomSimGenerator.myParameters = new HashMap<String, String>() private
Definition at line 17 of file RandomSimGenerator.java.
Referenced by controller.RandomSimGenerator.getParameters().
ResourceBundle controller.RandomSimGenerator.myProperties private
Definition at line 19 of file RandomSimGenerator.java.
Random controller.RandomSimGenerator.myRandom = new Random() private
Definition at line 20 of file RandomSimGenerator.java.
String controller.RandomSimGenerator.mySimName private
Definition at line 18 of file RandomSimGenerator.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team15/repository/src/controller/RandomSimGenerator.java