cellsociety_team15: view.ShapeGrid Class Reference
view.ShapeGrid Class Reference abstract
Public Member Functions
ShapeGrid (double gridWidth, double gridHeight, Shape colorGrid[][])
Shape[][] getColorGrid ()
Group createGrid (boolean stroke, double heightOfShape, double widthOfShape)
abstract Shape addShape (boolean stroke, double heightOfSquare, double widthOfSquare, int i, int j)
Protected Attributes
double myGridWidth
double myGridHeight
Private Attributes
Shape[][] myColorGrid
Detailed Description
Definition at line 6 of file ShapeGrid.java.
Constructor & Destructor Documentation
view.ShapeGrid.ShapeGrid (double gridWidth, double gridHeight, Shape colorGrid[][])
Definition at line 12 of file ShapeGrid.java.
Member Function Documentation
abstract Shape view.ShapeGrid.addShape (boolean stroke, double heightOfSquare, double widthOfSquare, int i, int j) abstract
Referenced by view.ShapeGrid.createGrid().
Group view.ShapeGrid.createGrid (boolean stroke, double heightOfShape, double widthOfShape)
Definition at line 22 of file ShapeGrid.java.
References view.ShapeGrid.addShape(), view.ShapeGrid.myGridHeight, and view.ShapeGrid.myGridWidth.
Referenced by view.SimulationScreen.initSimView().
Shape [][] view.ShapeGrid.getColorGrid ()
Definition at line 18 of file ShapeGrid.java.
References view.ShapeGrid.myColorGrid.
Member Data Documentation
Shape [][] view.ShapeGrid.myColorGrid private
Definition at line 10 of file ShapeGrid.java.
Referenced by view.ShapeGrid.getColorGrid().
double view.ShapeGrid.myGridHeight protected
Definition at line 9 of file ShapeGrid.java.
Referenced by view.ShapeGrid.createGrid().
double view.ShapeGrid.myGridWidth protected
Definition at line 8 of file ShapeGrid.java.
Referenced by view.ShapeGrid.createGrid().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team15/repository/src/view/ShapeGrid.java