cellsociety_team15: model.simulations.Simulation Class Reference
model.simulations.Simulation Class Reference abstract
Public Member Functions
Simulation (Map< String, String > paramMap, Map< String, String > styleMap, Integer[][] cellGrid, SimulationScreen simScreen) throws ValueException
void setParameter (String parameter, double value)
String patchType ()
abstract void updateGrid ()
void updateNeighborSquare (int row, int column)
Protected Attributes
SimulationScreen myView
int gridLength
int gridWidth
Patch[][] myPatchGrid
AbstractCellFactory myCellFactory
Neighbors myNeighbors
GridRules myGridRules
String directions
Package Functions
void parseStyleMap (Map< String, String > styleMap)
abstract AbstractCellFactory getCellFactory () throws ValueException
void fillPatchGrid ()
abstract void parseMap (Map< String, String > paramMap)
void setupGrid (Integer[][] grid)
void setupParameterControl ()
void updateColorGrid ()
void updateNeighbors ()
Detailed Description
Definition at line 18 of file Simulation.java.
Constructor & Destructor Documentation
model.simulations.Simulation.Simulation (Map< String, String > paramMap, Map< String, String > styleMap, Integer cellGrid[][], SimulationScreen simScreen) throws ValueException
Definition at line 35 of file Simulation.java.
References model.simulations.Simulation.fillPatchGrid(), model.simulations.Simulation.getCellFactory(), view.SimulationScreen.initSimView(), model.simulations.Simulation.parseMap(), model.simulations.Simulation.parseStyleMap(), model.simulations.Simulation.setupGrid(), and model.simulations.Simulation.setupParameterControl().
Member Function Documentation
void model.simulations.Simulation.fillPatchGrid () package
Definition at line 80 of file Simulation.java.
References model.neighbors.Neighbors.getAllNeighbors(), model.neighbors.Neighbors.getCardinalNeighbors(), model.neighbors.Neighbors.getDiagonalNeighbors(), model.simulations.PatchFactory.getPatch(), model.simulations.Simulation.gridLength, model.simulations.Simulation.gridWidth, model.simulations.Simulation.patchType(), and model.patches.Patch.setNeighbors().
Referenced by model.simulations.Simulation.Simulation().
abstract AbstractCellFactory model.simulations.Simulation.getCellFactory () throws ValueException abstract package
Referenced by model.simulations.Simulation.Simulation().
abstract void model.simulations.Simulation.parseMap (Map< String, String > paramMap) abstract package
Reads parameter map from XML file and sets instance variables accordingly
Referenced by model.simulations.Simulation.Simulation().
void model.simulations.Simulation.parseStyleMap (Map< String, String > styleMap) package
Parses through a map for styling options that can be applied to all simulations
Definition at line 59 of file Simulation.java.
Referenced by model.simulations.Simulation.Simulation().
String model.simulations.Simulation.patchType ()
Definition at line 104 of file Simulation.java.
Referenced by model.simulations.Simulation.fillPatchGrid().
void model.simulations.Simulation.setParameter (String parameter, double value)
Definition at line 77 of file Simulation.java.
Referenced by controller.CellSocietyController.changeSimulationParameters().
void model.simulations.Simulation.setupGrid (Integer grid[][]) package
fill grid with squares that have the right values given the parameters and the type of each space initialize grid, and fill
Parameters
paramMap
Definition at line 118 of file Simulation.java.
References model.simulations.AbstractCellFactory.getCell(), model.simulations.Simulation.gridLength, model.simulations.Simulation.gridWidth, model.patches.Patch.setCell(), model.cells.Cell.setPatch(), and model.simulations.Simulation.updateColorGrid().
Referenced by model.simulations.Simulation.Simulation().
void model.simulations.Simulation.setupParameterControl () package
Passes parameter names and values to view to allow the user to interactively change them
Definition at line 133 of file Simulation.java.
Referenced by model.simulations.Simulation.Simulation().
void model.simulations.Simulation.updateColorGrid () package
this method takes myGrid and turns it into a grid that is readable for the view
Definition at line 146 of file Simulation.java.
References model.patches.Patch.getCell(), model.cells.Cell.getColor(), model.patches.Patch.getColor(), model.simulations.Simulation.gridLength, model.simulations.Simulation.gridWidth, and view.SimulationScreen.updateScreen().
Referenced by model.simulations.Simulation.setupGrid(), model.simulations.SimulationLife.updateGrid(), model.simulations.SimulationSugarscape.updateGrid(), model.simulations.SimulationPredator.updateGrid(), model.simulations.SimulationFire.updateGrid(), and model.simulations.SimulationSegregation.updateGrid().
abstract void model.simulations.Simulation.updateGrid () abstract
Updates the grid by one frame
Referenced by controller.CellSocietyController.update().
void model.simulations.Simulation.updateNeighbors () package
Definition at line 163 of file Simulation.java.
References model.simulations.Simulation.gridLength, model.simulations.Simulation.gridWidth, and model.simulations.Simulation.updateNeighborSquare().
Referenced by model.simulations.SimulationLife.updateGrid(), model.simulations.SimulationSugarscape.updateGrid(), model.simulations.SimulationFire.updateGrid(), and model.simulations.SimulationSegregation.updateGrid().
void model.simulations.Simulation.updateNeighborSquare (int row, int column)
Definition at line 171 of file Simulation.java.
References model.patches.Patch.getCell(), and model.cells.Cell.setNeighbors().
Referenced by model.simulations.SimulationPredator.updateGrid(), and model.simulations.Simulation.updateNeighbors().
Member Data Documentation
String model.simulations.Simulation.directions protected
Definition at line 33 of file Simulation.java.
int model.simulations.Simulation.gridLength protected
Definition at line 27 of file Simulation.java.
Referenced by model.simulations.Simulation.fillPatchGrid(), model.simulations.SimulationSegregation.moveAgent(), model.simulations.SimulationFire.setParameter(), model.simulations.SimulationSegregation.setParameter(), model.simulations.SimulationPredator.setParameter(), model.simulations.Simulation.setupGrid(), model.simulations.SimulationPredator.SimulationPredator(), model.simulations.Simulation.updateColorGrid(), model.simulations.SimulationLife.updateGrid(), model.simulations.SimulationSugarscape.updateGrid(), model.simulations.SimulationPredator.updateGrid(), model.simulations.SimulationFire.updateGrid(), and model.simulations.Simulation.updateNeighbors().
int model.simulations.Simulation.gridWidth protected
Definition at line 28 of file Simulation.java.
Referenced by model.simulations.Simulation.fillPatchGrid(), model.simulations.SimulationSegregation.moveAgent(), model.simulations.SimulationFire.setParameter(), model.simulations.SimulationSegregation.setParameter(), model.simulations.SimulationPredator.setParameter(), model.simulations.Simulation.setupGrid(), model.simulations.SimulationPredator.SimulationPredator(), model.simulations.Simulation.updateColorGrid(), model.simulations.SimulationLife.updateGrid(), model.simulations.SimulationSugarscape.updateGrid(), model.simulations.SimulationPredator.updateGrid(), model.simulations.SimulationFire.updateGrid(), and model.simulations.Simulation.updateNeighbors().
AbstractCellFactory model.simulations.Simulation.myCellFactory protected
Definition at line 30 of file Simulation.java.
GridRules model.simulations.Simulation.myGridRules protected
Definition at line 32 of file Simulation.java.
Neighbors model.simulations.Simulation.myNeighbors protected
Definition at line 31 of file Simulation.java.
Patch [][] model.simulations.Simulation.myPatchGrid protected
Definition at line 29 of file Simulation.java.
Referenced by model.simulations.SimulationSegregation.moveAgent(), model.simulations.SimulationFire.setParameter(), model.simulations.SimulationSegregation.setParameter(), model.simulations.SimulationPredator.setParameter(), model.simulations.SimulationPredator.SimulationPredator(), model.simulations.SimulationLife.updateGrid(), model.simulations.SimulationSugarscape.updateGrid(), model.simulations.SimulationPredator.updateGrid(), model.simulations.SimulationFire.updateGrid(), and model.simulations.SimulationSegregation.updateGrid().
SimulationScreen model.simulations.Simulation.myView protected
Simulation superclass encompassing methods and data shared by all simulations and that will be used in updating the state of the simulation
Author
Janan
Definition at line 26 of file Simulation.java.
Referenced by model.simulations.SimulationFire.setupParameterControl(), model.simulations.SimulationPredator.setupParameterControl(), model.simulations.SimulationSugarscape.setupParameterControl(), and model.simulations.SimulationSegregation.setupParameterControl().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team15/repository/src/model/simulations/Simulation.java