cellsociety_team15: view.SimulationScreen Class Reference
view.SimulationScreen Class Reference
Public Member Functions
void initSimScreen (int width, int height, CellSocietyController controller, Map< String, String > styleMap)
BorderPane getNode ()
void createOptionsPanel (String[] names, double[] value, double[] min, double[] max)
void updateScreen (Color[][] colorGrid)
void initSimView (int gridHeight, int gridWidth)
Private Member Functions
HBox addButtons ()
void updateData (Color[][] colorGrid)
void updateMapArrayList (HashMap< Color, Integer > countMap, Color key)
Private Attributes
CellSocietyController myController
int myWidth
int myHeight
BorderPane root
ArrayList< Button > myButtons
HBox myTop
Map< String, String > myStyles
Shape[][] myColorGrid
Map< Color, ArrayList< Integer > > myData
Detailed Description
This class begins setting up the general simulation scene. This includes things like adding the four buttons at the top that load, step through, speed up, and stop/start the simulation. Note: all strings used to create buttons must be retrieved from a .properties file.
Author
Sunjeev
Definition at line 26 of file SimulationScreen.java.
Member Function Documentation
HBox view.SimulationScreen.addButtons () private
Definition at line 54 of file SimulationScreen.java.
References view.SimulationScreen.myTop.
Referenced by view.SimulationScreen.initSimScreen().
void view.SimulationScreen.createOptionsPanel (String[] names, double[] value, double[] min, double[] max)
Definition at line 66 of file SimulationScreen.java.
References view.SideMenu.createOptionWindow().
Referenced by model.simulations.SimulationFire.setupParameterControl(), model.simulations.SimulationPredator.setupParameterControl(), model.simulations.SimulationSugarscape.setupParameterControl(), and model.simulations.SimulationSegregation.setupParameterControl().
BorderPane view.SimulationScreen.getNode ()
Definition at line 50 of file SimulationScreen.java.
References view.SimulationScreen.root.
Referenced by controller.CellSocietyController.initializeSimulationScreen().
void view.SimulationScreen.initSimScreen (int width, int height, CellSocietyController controller, Map< String, String > styleMap)
Definition at line 37 of file SimulationScreen.java.
References view.SimulationScreen.addButtons().
Referenced by controller.CellSocietyController.initializeSimulationScreen().
void view.SimulationScreen.initSimView (int gridHeight, int gridWidth)
Called from the simulation. If it is a triangle type, it forms triangles, if it is rectangular it forms rectangles
Parameters
gridHeight
gridWidth
Definition at line 127 of file SimulationScreen.java.
References view.ShapeGrid.createGrid().
Referenced by model.simulations.Simulation.Simulation().
void view.SimulationScreen.updateData (Color colorGrid[][]) private
Definition at line 90 of file SimulationScreen.java.
References view.SimulationScreen.updateMapArrayList().
Referenced by view.SimulationScreen.updateScreen().
void view.SimulationScreen.updateMapArrayList (HashMap< Color, Integer > countMap, Color key) private
Definition at line 114 of file SimulationScreen.java.
Referenced by view.SimulationScreen.updateData().
void view.SimulationScreen.updateScreen (Color colorGrid[][])
must be passed a grid of some type so that it can determine the colors of each square It will then go through each square and set its appropriate color
Parameters
colorGrid
Definition at line 80 of file SimulationScreen.java.
References view.SimulationScreen.updateData().
Referenced by model.simulations.Simulation.updateColorGrid().
Member Data Documentation
ArrayList<Button> view.SimulationScreen.myButtons private
Definition at line 31 of file SimulationScreen.java.
Shape [][] view.SimulationScreen.myColorGrid private
Definition at line 34 of file SimulationScreen.java.
CellSocietyController view.SimulationScreen.myController private
Definition at line 27 of file SimulationScreen.java.
Map<Color, ArrayList<Integer> > view.SimulationScreen.myData private
Definition at line 35 of file SimulationScreen.java.
int view.SimulationScreen.myHeight private
Definition at line 29 of file SimulationScreen.java.
Map<String, String> view.SimulationScreen.myStyles private
Definition at line 33 of file SimulationScreen.java.
HBox view.SimulationScreen.myTop private
Definition at line 32 of file SimulationScreen.java.
Referenced by view.SimulationScreen.addButtons().
int view.SimulationScreen.myWidth private
Definition at line 28 of file SimulationScreen.java.
BorderPane view.SimulationScreen.root private
Definition at line 30 of file SimulationScreen.java.
Referenced by view.SimulationScreen.getNode().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team15/repository/src/view/SimulationScreen.java