cellsociety_team15: model.simulations.SimulationFire Class Reference
model.simulations.SimulationFire Class Reference
Public Member Functions
SimulationFire (Map< String, String > paramMap, Map< String, String > styleMap, Integer[][] grid, SimulationScreen simScreen)
void setParameter (String parameter, double value)
void updateGrid ()
Public Member Functions inherited from model.simulations.Simulation
Simulation (Map< String, String > paramMap, Map< String, String > styleMap, Integer[][] cellGrid, SimulationScreen simScreen) throws ValueException
void setParameter (String parameter, double value)
String patchType ()
abstract void updateGrid ()
void updateNeighborSquare (int row, int column)
Package Functions
void setupParameterControl ()
void parseMap (Map< String, String > paramMap)
AbstractCellFactory getCellFactory ()
Package Functions inherited from model.simulations.Simulation
void parseStyleMap (Map< String, String > styleMap)
abstract AbstractCellFactory getCellFactory () throws ValueException
void fillPatchGrid ()
abstract void parseMap (Map< String, String > paramMap)
void setupGrid (Integer[][] grid)
void setupParameterControl ()
void updateColorGrid ()
void updateNeighbors ()
Private Attributes
int myProbCatch
Additional Inherited Members
Protected Attributes inherited from model.simulations.Simulation
SimulationScreen myView
int gridLength
int gridWidth
Patch[][] myPatchGrid
AbstractCellFactory myCellFactory
Neighbors myNeighbors
GridRules myGridRules
String directions
Detailed Description
Fire simulation class that extends simulation superclass
Author
Sid
Definition at line 12 of file SimulationFire.java.
Constructor & Destructor Documentation
model.simulations.SimulationFire.SimulationFire (Map< String, String > paramMap, Map< String, String > styleMap, Integer grid[][], SimulationScreen simScreen)
Definition at line 16 of file SimulationFire.java.
Member Function Documentation
AbstractCellFactory model.simulations.SimulationFire.getCellFactory () package
Definition at line 72 of file SimulationFire.java.
void model.simulations.SimulationFire.parseMap (Map< String, String > paramMap) package
Definition at line 45 of file SimulationFire.java.
void model.simulations.SimulationFire.setParameter (String parameter, double value)
Definition at line 34 of file SimulationFire.java.
References model.patches.Patch.getCell(), model.simulations.Simulation.gridLength, model.simulations.Simulation.gridWidth, model.simulations.Simulation.myPatchGrid, and model.cells.Cell.setProperty().
void model.simulations.SimulationFire.setupParameterControl () package
Looks through parameters and puts them into instance variables
Definition at line 25 of file SimulationFire.java.
References view.SimulationScreen.createOptionsPanel(), and model.simulations.Simulation.myView.
void model.simulations.SimulationFire.updateGrid ()
Updates grid based on cell's update methods
Definition at line 60 of file SimulationFire.java.
References model.simulations.Simulation.gridLength, model.simulations.Simulation.gridWidth, model.simulations.Simulation.myPatchGrid, model.patches.Patch.setCell(), model.simulations.Simulation.updateColorGrid(), and model.simulations.Simulation.updateNeighbors().
Member Data Documentation
int model.simulations.SimulationFire.myProbCatch private
Definition at line 14 of file SimulationFire.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team15/repository/src/model/simulations/SimulationFire.java