cellsociety_team15: view.TopMenu Class Reference
view.TopMenu Class Reference
Public Member Functions
TopMenu (int width, int height, CellSocietyController controller, Map< Color, ArrayList< Integer >> myData2)
List< Button > createTopButtons ()
Private Member Functions
void addGraphButton ()
void addLoadButton ()
void addSlowDownButton ()
void addStepButton ()
void addSpeedUpButton ()
void addStopStartButton ()
Private Attributes
ResourceBundle myProperties
int myHeight
int myWidth
CellSocietyController myController
List< Button > myButtons
boolean myStart
Map< Color, ArrayList< Integer > > myData
Detailed Description
Definition at line 19 of file TopMenu.java.
Constructor & Destructor Documentation
view.TopMenu.TopMenu (int width, int height, CellSocietyController controller, Map< Color, ArrayList< Integer >> myData2)
Definition at line 29 of file TopMenu.java.
Member Function Documentation
void view.TopMenu.addGraphButton () private
Definition at line 50 of file TopMenu.java.
Referenced by view.TopMenu.createTopButtons().
void view.TopMenu.addLoadButton () private
This function adds the load button to the scene and creates the eventListener.
Returns
Button that loads new file
Definition at line 87 of file TopMenu.java.
References controller.CellSocietyController.transitionToFileLoaderScreen().
Referenced by view.TopMenu.createTopButtons().
void view.TopMenu.addSlowDownButton () private
Definition at line 95 of file TopMenu.java.
References controller.CellSocietyController.changeSimulationSpeed().
Referenced by view.TopMenu.createTopButtons().
void view.TopMenu.addSpeedUpButton () private
Adds speed up button
Definition at line 117 of file TopMenu.java.
References controller.CellSocietyController.changeSimulationSpeed().
Referenced by view.TopMenu.createTopButtons().
void view.TopMenu.addStepButton () private
This function adds the step button to the scene and creates the eventListener.
Definition at line 106 of file TopMenu.java.
References controller.CellSocietyController.stepThroughSimulation().
Referenced by view.TopMenu.createTopButtons().
void view.TopMenu.addStopStartButton () private
adds stop.start button
Returns
Definition at line 130 of file TopMenu.java.
References view.TopMenu.myStart, and controller.CellSocietyController.stopOrStart().
Referenced by view.TopMenu.createTopButtons().
List<Button> view.TopMenu.createTopButtons ()
Definition at line 39 of file TopMenu.java.
References view.TopMenu.addGraphButton(), view.TopMenu.addLoadButton(), view.TopMenu.addSlowDownButton(), view.TopMenu.addSpeedUpButton(), view.TopMenu.addStepButton(), view.TopMenu.addStopStartButton(), and view.TopMenu.myButtons.
Member Data Documentation
List<Button> view.TopMenu.myButtons private
Definition at line 25 of file TopMenu.java.
Referenced by view.TopMenu.createTopButtons().
CellSocietyController view.TopMenu.myController private
Definition at line 24 of file TopMenu.java.
Map<Color, ArrayList<Integer> > view.TopMenu.myData private
Definition at line 27 of file TopMenu.java.
int view.TopMenu.myHeight private
Definition at line 22 of file TopMenu.java.
ResourceBundle view.TopMenu.myProperties private
Definition at line 21 of file TopMenu.java.
boolean view.TopMenu.myStart private
Definition at line 26 of file TopMenu.java.
Referenced by view.TopMenu.addStopStartButton().
int view.TopMenu.myWidth private
Definition at line 23 of file TopMenu.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team15/repository/src/view/TopMenu.java