cellsociety_team15: view.SideMenu Class Reference
view.SideMenu Class Reference
Public Member Functions
SideMenu (int width, int height, String[] names, double[] values, double[] min, double[] max, CellSocietyController controller)
void createOptionWindow ()
Private Member Functions
Node addOptionsPanel ()
Private Attributes
int myWidth
int myHeight
String[] myNames
double[] myValues
double[] myMins
double[] myMaxs
CellSocietyController myController
Detailed Description
Definition at line 15 of file SideMenu.java.
Constructor & Destructor Documentation
view.SideMenu.SideMenu (int width, int height, String[] names, double[] values, double[] min, double[] max, CellSocietyController controller)
Definition at line 29 of file SideMenu.java.
Member Function Documentation
Node view.SideMenu.addOptionsPanel () private
Definition at line 53 of file SideMenu.java.
References controller.CellSocietyController.changeSimulationParameters().
Referenced by view.SideMenu.createOptionWindow().
void view.SideMenu.createOptionWindow ()
Definition at line 40 of file SideMenu.java.
References view.SideMenu.addOptionsPanel().
Referenced by view.SimulationScreen.createOptionsPanel().
Member Data Documentation
CellSocietyController view.SideMenu.myController private
Definition at line 27 of file SideMenu.java.
int view.SideMenu.myHeight private
Definition at line 22 of file SideMenu.java.
double [] view.SideMenu.myMaxs private
Definition at line 26 of file SideMenu.java.
double [] view.SideMenu.myMins private
Definition at line 25 of file SideMenu.java.
String [] view.SideMenu.myNames private
Definition at line 23 of file SideMenu.java.
double [] view.SideMenu.myValues private
Definition at line 24 of file SideMenu.java.
int view.SideMenu.myWidth private
Definition at line 21 of file SideMenu.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team15/repository/src/view/SideMenu.java