cellsociety_team15: controller.XMLParser Class Reference
controller.XMLParser Class Reference
Public Member Functions
XMLParser (File XMLFile) throws InvalidParameterException
Integer[][] getGrid ()
HashMap< String, String > getParameters ()
Static Public Member Functions
static void clean (Node node)
Private Member Functions
void readStyleFile (Document doc)
void readSimFile (Document doc) throws InvalidParameterException
void checkFileExtension (File xmlFile)
void createGrid (NodeList gridChildren)
void readParameters (NodeList parameterChildren) throws InvalidParameterException
void readGrid (NodeList gridChildren) throws ArrayIndexOutOfBoundsException
NodeList initializeNodeList (Document doc, String element)
Document initializeDoc (File XMLFile) throws ParserConfigurationException, SAXException, IOException
Private Attributes
HashMap< String, String > myParameters = new HashMap<String, String>()
Integer myGrid [][]
Detailed Description
This is the XML parser class called by the controller It reads in an xml file in the specified format and outputs the grid and parameter hashmap
Author
Sid
Definition at line 25 of file XMLParser.java.
Constructor & Destructor Documentation
controller.XMLParser.XMLParser (File XMLFile) throws InvalidParameterException
Definition at line 30 of file XMLParser.java.
References controller.XMLParser.checkFileExtension(), controller.XMLParser.clean(), controller.XMLParser.initializeDoc(), controller.XMLParser.readSimFile(), and controller.XMLParser.readStyleFile().
Member Function Documentation
void controller.XMLParser.checkFileExtension (File xmlFile) private
Method to check file extension name Could be made a try/catch but didn't due to time
Parameters
xmlFile
Definition at line 76 of file XMLParser.java.
Referenced by controller.XMLParser.XMLParser().
static void controller.XMLParser.clean (Node node) static
Method that cleans white space and stray characters out of XML file Taken from: http://stackoverflow.com/questions/978810/how-to-strip-whitespace-only -text-nodes-from-a-dom-before-serialization/16285664#16285664
Parameters
node
Definition at line 120 of file XMLParser.java.
Referenced by controller.XMLParser.XMLParser().
void controller.XMLParser.createGrid (NodeList gridChildren) private
Initialize grid size
Parameters
gridChildren
Definition at line 88 of file XMLParser.java.
Referenced by controller.XMLParser.readSimFile().
Integer [][] controller.XMLParser.getGrid ()
Returns myGrid Called by controller
Definition at line 189 of file XMLParser.java.
References controller.XMLParser.myGrid.
Referenced by controller.CellSocietyController.readXML().
HashMap<String, String> controller.XMLParser.getParameters ()
Returns HashMap of parameters Called by controller
Definition at line 197 of file XMLParser.java.
References controller.XMLParser.myParameters.
Referenced by controller.CellSocietyController.readXML().
Document controller.XMLParser.initializeDoc (File XMLFile) throws ParserConfigurationException, SAXException, IOException private
Does initial set-up of document file.
Definition at line 176 of file XMLParser.java.
Referenced by controller.XMLParser.XMLParser().
NodeList controller.XMLParser.initializeNodeList (Document doc, String element) private
Function to do initial set-up Returns a node list of all elements of one type Ex. returns list of parameters or list of grid rows
Definition at line 165 of file XMLParser.java.
Referenced by controller.XMLParser.readSimFile(), and controller.XMLParser.readStyleFile().
void controller.XMLParser.readGrid (NodeList gridChildren) throws ArrayIndexOutOfBoundsException private
Read in the Grid row by row Create the new cells by placing ints in the grid array
Definition at line 144 of file XMLParser.java.
Referenced by controller.XMLParser.readSimFile().
void controller.XMLParser.readParameters (NodeList parameterChildren) throws InvalidParameterException private
Read in the parameters Put them in the HashMap Also used to read in the parameters in the style sheet Uses a messy if statement to throw the exception
Definition at line 100 of file XMLParser.java.
Referenced by controller.XMLParser.readSimFile(), and controller.XMLParser.readStyleFile().
void controller.XMLParser.readSimFile (Document doc) throws InvalidParameterException private
Reads a sim file document Puts all parameters in the parameter map Creates grid and puts it in grid array
Parameters
doc
Exceptions
InvalidParameterException
Definition at line 63 of file XMLParser.java.
References controller.XMLParser.createGrid(), controller.XMLParser.initializeNodeList(), controller.XMLParser.readGrid(), and controller.XMLParser.readParameters().
Referenced by controller.XMLParser.XMLParser().
void controller.XMLParser.readStyleFile (Document doc) private
Reads the style file document using the read Parameters method
Parameters
doc
Definition at line 51 of file XMLParser.java.
References controller.XMLParser.initializeNodeList(), and controller.XMLParser.readParameters().
Referenced by controller.XMLParser.XMLParser().
Member Data Documentation
Integer controller.XMLParser.myGrid[][] private
Definition at line 28 of file XMLParser.java.
Referenced by controller.XMLParser.getGrid().
HashMap<String, String> controller.XMLParser.myParameters = new HashMap<String, String>() private
Definition at line 27 of file XMLParser.java.
Referenced by controller.XMLParser.getParameters().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team15/repository/src/controller/XMLParser.java