cellsociety_team15: view.FileLoaderScreen Class Reference
view.FileLoaderScreen Class Reference
Public Member Functions
FileLoaderScreen (Stage stage)
Node getNode ()
File getFile ()
Package Attributes
final FileChooser fileChooser
Stage myStage
Scene myScene
Static Private Member Functions
static void configureFileChooser (final FileChooser fileChooser)
Static Private Attributes
static ResourceBundle myProperties
Detailed Description
Definition at line 18 of file FileLoaderScreen.java.
Constructor & Destructor Documentation
view.FileLoaderScreen.FileLoaderScreen (Stage stage)
Definition at line 25 of file FileLoaderScreen.java.
Member Function Documentation
static void view.FileLoaderScreen.configureFileChooser (final FileChooser fileChooser) static private
Definition at line 55 of file FileLoaderScreen.java.
Referenced by view.FileLoaderScreen.getFile().
File view.FileLoaderScreen.getFile ()
Definition at line 49 of file FileLoaderScreen.java.
References view.FileLoaderScreen.configureFileChooser().
Referenced by controller.CellSocietyController.transitionToFileLoaderScreen().
Node view.FileLoaderScreen.getNode ()
Definition at line 31 of file FileLoaderScreen.java.
Referenced by controller.CellSocietyController.transitionToFileLoaderScreen().
Member Data Documentation
final FileChooser view.FileLoaderScreen.fileChooser package
Definition at line 20 of file FileLoaderScreen.java.
ResourceBundle view.FileLoaderScreen.myProperties static private
Definition at line 23 of file FileLoaderScreen.java.
Scene view.FileLoaderScreen.myScene package
Definition at line 22 of file FileLoaderScreen.java.
Stage view.FileLoaderScreen.myStage package
Definition at line 21 of file FileLoaderScreen.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team15/repository/src/view/FileLoaderScreen.java