cellsociety_team15: model.simulations.SimulationSegregation Class Reference
model.simulations.SimulationSegregation Class Reference
Public Member Functions
SimulationSegregation (Map< String, String > paramMap, Map< String, String > styleMap, Integer[][] grid, SimulationScreen simScreen)
void setParameter (String parameter, double value)
void updateGrid ()
Public Member Functions inherited from model.simulations.Simulation
Simulation (Map< String, String > paramMap, Map< String, String > styleMap, Integer[][] cellGrid, SimulationScreen simScreen) throws ValueException
void setParameter (String parameter, double value)
String patchType ()
abstract void updateGrid ()
void updateNeighborSquare (int row, int column)
Package Functions
void parseMap (Map< String, String > paramMap)
void setupParameterControl ()
AbstractCellFactory getCellFactory ()
Package Functions inherited from model.simulations.Simulation
void parseStyleMap (Map< String, String > styleMap)
abstract AbstractCellFactory getCellFactory () throws ValueException
void fillPatchGrid ()
abstract void parseMap (Map< String, String > paramMap)
void setupGrid (Integer[][] grid)
void setupParameterControl ()
void updateColorGrid ()
void updateNeighbors ()
Private Member Functions
void moveAgent (int j, int i, Cell clone)
Private Attributes
Random myRandom
double mySatisfaction
Static Private Attributes
static final int SAFE_GUARD = 1000
Additional Inherited Members
Protected Attributes inherited from model.simulations.Simulation
SimulationScreen myView
int gridLength
int gridWidth
Patch[][] myPatchGrid
AbstractCellFactory myCellFactory
Neighbors myNeighbors
GridRules myGridRules
String directions
Detailed Description
Segregation simulation Extension of simulation superclass
Author
Sunjeev and Sid
Definition at line 16 of file SimulationSegregation.java.
Constructor & Destructor Documentation
model.simulations.SimulationSegregation.SimulationSegregation (Map< String, String > paramMap, Map< String, String > styleMap, Integer grid[][], SimulationScreen simScreen)
Definition at line 22 of file SimulationSegregation.java.
Member Function Documentation
AbstractCellFactory model.simulations.SimulationSegregation.getCellFactory () package
Definition at line 105 of file SimulationSegregation.java.
void model.simulations.SimulationSegregation.moveAgent (int j, int i, Cell clone) private
Moves a cell that isn't satisfied
Parameters
j
i
clone
Definition at line 85 of file SimulationSegregation.java.
References model.simulations.Simulation.gridLength, model.simulations.Simulation.gridWidth, model.simulations.Simulation.myPatchGrid, and model.patches.Patch.setCell().
Referenced by model.simulations.SimulationSegregation.updateGrid().
void model.simulations.SimulationSegregation.parseMap (Map< String, String > paramMap) package
Looks through paramMap and puts values into appropriate instance variables
Definition at line 33 of file SimulationSegregation.java.
void model.simulations.SimulationSegregation.setParameter (String parameter, double value)
Definition at line 53 of file SimulationSegregation.java.
References model.patches.Patch.getCell(), model.simulations.Simulation.gridLength, model.simulations.Simulation.gridWidth, model.simulations.Simulation.myPatchGrid, and model.cells.Cell.setProperty().
void model.simulations.SimulationSegregation.setupParameterControl () package
Definition at line 45 of file SimulationSegregation.java.
References view.SimulationScreen.createOptionsPanel(), and model.simulations.Simulation.myView.
void model.simulations.SimulationSegregation.updateGrid ()
Updates the grid by looking at each cell and whether it should move
Definition at line 66 of file SimulationSegregation.java.
References model.patches.Patch.getCell(), model.simulations.SimulationSegregation.moveAgent(), model.simulations.Simulation.myPatchGrid, model.cells.Cell.update(), model.simulations.Simulation.updateColorGrid(), and model.simulations.Simulation.updateNeighbors().
Member Data Documentation
Random model.simulations.SimulationSegregation.myRandom private
Definition at line 19 of file SimulationSegregation.java.
double model.simulations.SimulationSegregation.mySatisfaction private
Definition at line 20 of file SimulationSegregation.java.
final int model.simulations.SimulationSegregation.SAFE_GUARD = 1000 static private
Definition at line 18 of file SimulationSegregation.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team15/repository/src/model/simulations/SimulationSegregation.java