cellsociety_team15: model.simulations.SimulationPredator Class Reference
model.simulations.SimulationPredator Class Reference
Public Member Functions
SimulationPredator (Map< String, String > paramMap, Map< String, String > styleMap, Integer[][] initGrid, SimulationScreen simscreen)
void parseMap (Map< String, String > paramMap)
void updateGrid ()
void setParameter (String parameter, double value)
Public Member Functions inherited from model.simulations.Simulation
Simulation (Map< String, String > paramMap, Map< String, String > styleMap, Integer[][] cellGrid, SimulationScreen simScreen) throws ValueException
void setParameter (String parameter, double value)
String patchType ()
abstract void updateGrid ()
void updateNeighborSquare (int row, int column)
Package Functions
void setupParameterControl ()
AbstractCellFactory getCellFactory ()
Package Functions inherited from model.simulations.Simulation
void parseStyleMap (Map< String, String > styleMap)
abstract AbstractCellFactory getCellFactory () throws ValueException
void fillPatchGrid ()
abstract void parseMap (Map< String, String > paramMap)
void setupGrid (Integer[][] grid)
void setupParameterControl ()
void updateColorGrid ()
void updateNeighbors ()
Private Attributes
int sharkLife
int breedingPeriod
boolean[][] movedGrid
Additional Inherited Members
Protected Attributes inherited from model.simulations.Simulation
SimulationScreen myView
int gridLength
int gridWidth
Patch[][] myPatchGrid
AbstractCellFactory myCellFactory
Neighbors myNeighbors
GridRules myGridRules
String directions
Detailed Description
Subclass of Simulation for the Predator-Prey CA simulation. Contains methods and data necessary to run simulation
Author
Janan
Definition at line 14 of file SimulationPredator.java.
Constructor & Destructor Documentation
model.simulations.SimulationPredator.SimulationPredator (Map< String, String > paramMap, Map< String, String > styleMap, Integer initGrid[][], SimulationScreen simscreen)
Definition at line 19 of file SimulationPredator.java.
References model.patches.Patch.getCell(), model.simulations.Simulation.gridLength, model.simulations.Simulation.gridWidth, model.simulations.Simulation.myPatchGrid, and model.cells.Cell.setCoords().
Member Function Documentation
AbstractCellFactory model.simulations.SimulationPredator.getCellFactory () package
Definition at line 100 of file SimulationPredator.java.
void model.simulations.SimulationPredator.parseMap (Map< String, String > paramMap)
Definition at line 40 of file SimulationPredator.java.
void model.simulations.SimulationPredator.setParameter (String parameter, double value)
Definition at line 105 of file SimulationPredator.java.
References model.patches.Patch.getCell(), model.simulations.Simulation.gridLength, model.simulations.Simulation.gridWidth, model.simulations.Simulation.myPatchGrid, and model.cells.Cell.setProperty().
void model.simulations.SimulationPredator.setupParameterControl () package
Definition at line 32 of file SimulationPredator.java.
References model.simulations.SimulationPredator.breedingPeriod, view.SimulationScreen.createOptionsPanel(), and model.simulations.Simulation.myView.
void model.simulations.SimulationPredator.updateGrid ()
Definition at line 57 of file SimulationPredator.java.
References model.patches.Patch.getCell(), model.cells.Cell.getX(), model.cells.Cell.getY(), model.simulations.Simulation.gridLength, model.simulations.Simulation.gridWidth, model.simulations.Simulation.myPatchGrid, model.patches.Patch.setCell(), model.cells.Cell.setCoords(), model.cells.Cell.update(), model.simulations.Simulation.updateColorGrid(), model.simulations.Simulation.updateNeighborSquare(), and model.cells.Cell.viewProperties().
Member Data Documentation
int model.simulations.SimulationPredator.breedingPeriod private
Definition at line 16 of file SimulationPredator.java.
Referenced by model.simulations.SimulationPredator.setupParameterControl().
boolean [][] model.simulations.SimulationPredator.movedGrid private
Definition at line 17 of file SimulationPredator.java.
int model.simulations.SimulationPredator.sharkLife private
Definition at line 15 of file SimulationPredator.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team15/repository/src/model/simulations/SimulationPredator.java