cellsociety_team15: controller.ProbabilitySimGenerator Class Reference
controller.ProbabilitySimGenerator Class Reference
Public Member Functions
ProbabilitySimGenerator (int gridHeight, int gridWidth, String simName, HashMap< Integer, Integer > probabilities)
Public Member Functions inherited from controller.SimGenerator
SimGenerator (int gridHeight, int gridWidth, String simName, HashMap< Integer, Integer > probabilities, String gridType)
Integer[][] getGrid ()
HashMap< String, String > getParameters ()
Protected Member Functions
void createGrid (Integer[][] grid)
Protected Member Functions inherited from controller.SimGenerator
abstract void createGrid (Integer[][] grid)
Private Member Functions
void generateCellValue (int i, int j)
Private Attributes
HashMap< Integer, Integer > myProbabilities
Additional Inherited Members
Protected Attributes inherited from controller.SimGenerator
Integer[][] myGrid
HashMap< String, String > myParameters = new HashMap<String, String>()
String mySimName
Random myRandom = new Random()
ResourceBundle myProperties
Detailed Description
This generator creates a random grid Based on probabilities that it is passed in a map Each cell's state is generated based on a probability
Author
Sid
Definition at line 16 of file ProbabilitySimGenerator.java.
Constructor & Destructor Documentation
controller.ProbabilitySimGenerator.ProbabilitySimGenerator (int gridHeight, int gridWidth, String simName, HashMap< Integer, Integer > probabilities)
Sets up grid generator Puts basic values into parameter map
Parameters
gridHeight
gridWidth
simName
probabilities
Definition at line 28 of file ProbabilitySimGenerator.java.
References controller.ProbabilitySimGenerator.createGrid(), and controller.SimGenerator.myGrid.
Member Function Documentation
void controller.ProbabilitySimGenerator.createGrid (Integer grid[][]) protected
Iterates through grid array Calls generate cell value on each cell
Parameters
grid
Definition at line 41 of file ProbabilitySimGenerator.java.
References controller.ProbabilitySimGenerator.generateCellValue().
Referenced by controller.ProbabilitySimGenerator.ProbabilitySimGenerator().
void controller.ProbabilitySimGenerator.generateCellValue (int i, int j) private
Checks a random number against a cell state probability
Parameters
i
j
Definition at line 54 of file ProbabilitySimGenerator.java.
References controller.SimGenerator.myGrid, and controller.SimGenerator.myRandom.
Referenced by controller.ProbabilitySimGenerator.createGrid().
Member Data Documentation
HashMap<Integer, Integer> controller.ProbabilitySimGenerator.myProbabilities private
Definition at line 18 of file ProbabilitySimGenerator.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team15/repository/src/controller/ProbabilitySimGenerator.java