cellsociety_team15: model.gridrules.GridRules Class Reference
model.gridrules.GridRules Class Reference abstract
Public Member Functions
abstract void handleEdges (Patch[][] grid, int x, int y, List< Patch > list)
Detailed Description
Definition at line 5 of file GridRules.java.
Member Function Documentation
abstract void model.gridrules.GridRules.handleEdges (Patch grid[][], int x, int y, List< Patch > list) abstract
Referenced by model.neighbors.Neighbors.bottomLeft(), model.neighbors.Neighbors.bottomRight(), model.neighbors.Neighbors.Down(), model.neighbors.Neighbors.Left(), model.neighbors.Neighbors.Right(), model.neighbors.Neighbors.topLeft(), model.neighbors.Neighbors.topRight(), and model.neighbors.Neighbors.Up().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team15/repository/src/model/gridrules/GridRules.java