cellsociety_team15: model.cells.PredatorCellFish Class Reference
model.cells.PredatorCellFish Class Reference
Public Member Functions
PredatorCellFish (int breedingPeriod)
Cell update ()
Cell moveSquareTo ()
Color getColor ()
Public Member Functions inherited from model.cells.PredatorCell
PredatorCell (int breedingPeriod)
abstract Cell update ()
abstract Cell moveSquareTo ()
void decrementBreeding ()
Public Member Functions inherited from model.cells.Cell
abstract Color getColor ()
void setNeighbors (List< Cell > neighbors)
Cell ()
Map< String, Double > viewProperties ()
void setCoords (int x, int y)
int getX ()
int getY ()
void setProperty (String property, Double value)
abstract Cell update ()
void setPatch (Patch patch)
Additional Inherited Members
Protected Attributes inherited from model.cells.Cell
List< Cell > myNeighbors
Map< String, Double > myPropertyMap
int myX
int myY
Patch myPatch
Static Package Attributes inherited from model.cells.PredatorCell
static final String myBreedingPeriod = "myBreedingPeriod"
static final String myCurrentBreeding = "myCurrentBreeding"
static final String isEdible = "isEdible"
static final String isMovable = "isMovable"
Detailed Description
Definition at line 8 of file PredatorCellFish.java.
Constructor & Destructor Documentation
model.cells.PredatorCellFish.PredatorCellFish (int breedingPeriod)
Subclass of SquarePredator representing a square with fish
Parameters
breedingPeriod
x
y
Definition at line 17 of file PredatorCellFish.java.
References model.cells.PredatorCell.isEdible, model.cells.PredatorCell.isMovable, and model.cells.Cell.myPropertyMap.
Member Function Documentation
Color model.cells.PredatorCellFish.getColor ()
Definition at line 50 of file PredatorCellFish.java.
Cell model.cells.PredatorCellFish.moveSquareTo ()
Definition at line 30 of file PredatorCellFish.java.
References model.cells.Cell.getX(), model.cells.Cell.getY(), model.cells.PredatorCell.isMovable, model.cells.Cell.myNeighbors, and model.cells.Cell.setCoords().
Referenced by model.cells.PredatorCellFish.update().
Cell model.cells.PredatorCellFish.update ()
Definition at line 24 of file PredatorCellFish.java.
References model.cells.PredatorCellFish.moveSquareTo().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team15/repository/src/model/cells/PredatorCellFish.java