cellsociety_team15: model.neighbors.SquareTriangleNeighbors Class Reference
model.neighbors.SquareTriangleNeighbors Class Reference
Public Member Functions
List< Patch > getCardinalNeighbors (Patch[][] grid, int x, int y, GridRules rules)
List< Patch > getDiagonalNeighbors (Patch[][] grid, int x, int y, GridRules rules)
List< Patch > getAllNeighbors (Patch[][] grid, int x, int y, GridRules rules)
Public Member Functions inherited from model.neighbors.Neighbors
abstract List< Patch > getCardinalNeighbors (Patch[][] grid, int x, int y, GridRules rules)
abstract List< Patch > getDiagonalNeighbors (Patch[][] grid, int x, int y, GridRules rules)
abstract List< Patch > getAllNeighbors (Patch[][] grid, int x, int y, GridRules rules)
void topRight (Patch[][]grid, int x, int y, GridRules rules, List< Patch > neighbors)
void topLeft (Patch[][]grid, int x, int y, GridRules rules, List< Patch > neighbors)
void Right (Patch[][] grid, int x, int y, GridRules rules, List< Patch > neighbors)
void Left (Patch[][] grid, int x, int y, GridRules rules, List< Patch > neighbors)
void bottomRight (Patch[][] grid, int x, int y, GridRules rules, List< Patch > neighbors)
void bottomLeft (Patch[][] grid, int x, int y, GridRules rules, List< Patch > neighbors)
void Up (Patch[][] grid, int x, int y, GridRules rules, List< Patch > neighbors)
void Down (Patch[][] grid, int x, int y, GridRules rules, List< Patch > neighbors)
Detailed Description
Definition at line 8 of file SquareTriangleNeighbors.java.
Member Function Documentation
List<Patch> model.neighbors.SquareTriangleNeighbors.getAllNeighbors (Patch grid[][], int x, int y, GridRules rules)
Definition at line 31 of file SquareTriangleNeighbors.java.
References model.neighbors.SquareTriangleNeighbors.getCardinalNeighbors(), and model.neighbors.SquareTriangleNeighbors.getDiagonalNeighbors().
List<Patch> model.neighbors.SquareTriangleNeighbors.getCardinalNeighbors (Patch grid[][], int x, int y, GridRules rules)
Definition at line 11 of file SquareTriangleNeighbors.java.
References model.neighbors.Neighbors.Down(), model.neighbors.Neighbors.Left(), model.neighbors.Neighbors.Right(), and model.neighbors.Neighbors.Up().
Referenced by model.neighbors.SquareTriangleNeighbors.getAllNeighbors().
List<Patch> model.neighbors.SquareTriangleNeighbors.getDiagonalNeighbors (Patch grid[][], int x, int y, GridRules rules)
Definition at line 21 of file SquareTriangleNeighbors.java.
References model.neighbors.Neighbors.bottomLeft(), model.neighbors.Neighbors.bottomRight(), model.neighbors.Neighbors.topLeft(), and model.neighbors.Neighbors.topRight().
Referenced by model.neighbors.SquareTriangleNeighbors.getAllNeighbors().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/cellsociety_team15/repository/src/model/neighbors/SquareTriangleNeighbors.java